// 當季熱門

export const popularRecipe = [
  {
    id: 1,
    title: '味增馬鈴薯煎餅',
    image: '/src/assets/image/Recipes/popular-season/miso-potato.jpg',
    comments: 120,
    bookmarks: 90,
    time: 20,
    tag: ['#和風', '#馬鈴薯'],
  },
  {
    id: 2,
    title: '爆漿起司漢堡排',
    image: '/src/assets/image/Recipes/popular-season/cheese-hamburger-steak.jpg',
    comments: 90,
    bookmarks: 45,
    time: 15,
    tag: ['#和風', '#起司', '#牛肉'],
  },
  {
    id: 3,
    title: '日式照燒茄子丼',
    image: '/src/assets/image/Recipes/popular-season/scrambled-egg -rice.jpg',
    comments: 120,
    bookmarks: 60,
    time: 20,
    tag: ['#和風', '#飯', '#茄子'],
  },
  {
    id: 4,
    title: '奶油雞肉義大利麵',
    image: '/src/assets/image/Recipes/popular-season/creamy-chicken -pasta.jpg',
    comments: 105,
    bookmarks: 50,
    time: 20,
    tag: ['#雞肉', '#麵'],
  },
  {
    id: 5,
    title: '覆盆莓開心果慕斯蛋糕',
    image: '/src/assets/image/Recipes/popular-season/raspberry-mousse-cake.jpg',
    comments: 90,
    bookmarks: 45,
    time: 15,
    tag: ['#覆盆莓'],
  },
  {
    id: 6,
    title: '日式滑蛋丼',
    image: '/src/assets/image/Recipes/popular-season/eggplant-rice.jpg',
    comments: 120,
    bookmarks: 60,
    time: 20,
    tag: ['#蛋', '#飯'],
  },
  {
    id: 7,
    title: '玫瑰鹽奶油蜂蜜布丁',
    image: '/src/assets/image/Recipes/popular-season/honey-pudding.jpg',
    comments: 90,
    bookmarks: 45,
    time: 15,
    tag: ['#蜂蜜', '#布丁'],
  },
  {
    id: 8,
    title: '番茄薑香牛奶燉雞',
    image: '/src/assets/image/Recipes/popular-season/chicken-milk.jpg',
    comments: 90,
    bookmarks: 45,
    time: 15,
    tag: ['#番茄', '#雞肉'],
  },
  {
    id: 9,
    title: '和風高麗菜炒豆皮絲',
    image: '/src/assets/image/Recipes/popular-season/stir-fried-shredded-cabbage.jpg',
    comments: 120,
    bookmarks: 60,
    time: 20,
    tag: ['#和風', '#高麗菜'],
  },
];
