// 當季熱門

export const popularRecipe = [
  {
    id: 1,
    title: '味增馬鈴薯煎餅',
    image: '/src/assets/image/Recipes/popular-season/miso-potato.jpg',
    comments: 120,
    bookmarks: 90,
    time: 20,
    tag: ['#和風', '#馬鈴薯'],
  },
  {
    id: 2,
    title: '爆漿起司漢堡排',
    image: '/src/assets/image/Recipes/popular-season/cheese-hamburger-steak.jpg',
    comments: 90,
    bookmarks: 45,
    time: 15,
    tag: ['#和風', '#起司', '#牛肉'],
  },
  {
    id: 3,
    title: '日式照燒茄子丼',
    image: '/src/assets/image/Recipes/popular-season/scrambled-egg -rice.jpg',
    comments: 120,
    bookmarks: 60,
    time: 20,
    tag: ['#和風', '#飯', '#茄子'],
  },
  {
    id: 4,
    title: '奶油雞肉義大利麵',
    image: '/src/assets/image/Recipes/popular-season/creamy-chicken -pasta.jpg',
    comments: 105,
    bookmarks: 50,
    time: 20,
    tag: ['#雞肉', '#麵'],
  },
  {
    id: 5,
    title: '覆盆莓開心果慕斯蛋糕',
    image: '/src/assets/image/Recipes/popular-season/raspberry-mousse-cake.jpg',
    comments: 90,
    bookmarks: 45,
    time: 15,
    tag: ['#覆盆莓'],
  },
  {
    id: 6,
    title: '日式滑蛋丼',
    image: '/src/assets/image/Recipes/popular-season/eggplant-rice.jpg',
    comments: 120,
    bookmarks: 60,
    time: 20,
    tag: ['#蛋', '#飯'],
  },
  {
    id: 7,
    title: '玫瑰鹽奶油蜂蜜布丁',
    image: '/src/assets/image/Recipes/popular-season/honey-pudding.jpg',
    comments: 90,
    bookmarks: 45,
    time: 15,
    tag: ['#蜂蜜', '#布丁'],
  },
  {
    id: 8,
    title: '番茄薑香牛奶燉雞',
    image: '/src/assets/image/Recipes/popular-season/chicken-milk.jpg',
    comments: 90,
    bookmarks: 45,
    time: 15,
    tag: ['#番茄', '#雞肉'],
  },
  {
    id: 9,
    title: '和風高麗菜炒豆皮絲',
    image: '/src/assets/image/Recipes/popular-season/stir-fried-shredded-cabbage.jpg',
    comments: 120,
    bookmarks: 60,
    time: 20,
    tag: ['#和風', '#高麗菜'],
  },
];

//一人料理

export const soloMeal = [
  {
    id:1,
    title: '剝皮辣椒雞湯',
    image: '/src/assets/image/Recipes/solo-meal/peeled-chili- pepper-chicken -soup.jpg',
    comments: 105,
    bookmarks: 90,
    time: 20,
    tag: ['#雞肉'],
  },
  {
    id: 2,
    title: '黃金蝦仁蛋炒飯',
    image: '/src/assets/image/Recipes/solo-meal/golden-fried-rice.jpg',
    comments: 90,
    bookmarks: 45,
    time: 15,
    tag: ['#飯'],
  },
  {
    id: 3,
    title: '南洋風味海鮮叻沙麵',
    image: '/src/assets/image/Recipes/solo-meal/laksa.jpg',
    comments: 120,
    bookmarks: 60,
    time: 20,
    tag: ['#南洋', '#麵'],
  },
  {
    id: 4,
    title: '酪梨太陽蛋吐司',
    image: '/src/assets/image/Recipes/solo-meal/avocado-egg-toast.jpg',
    comments: 85,
    bookmarks: 30,
    time: 15,
    tag: ['#酪梨','#輕食'],
  },
  {
    id: 5,
    title: '經典雙層牛肉起司堡',
    image: '/src/assets/image/Recipes/solo-meal/double-cheeseburger.jpg',
    comments: 90,
    bookmarks: 45,
    time: 15,
    tag: ['#美式','#牛肉'],
  },
  {
    id: 6,
    title: '楓糖藍莓鬆餅',
    image: '/src/assets/image/Recipes/solo-meal/blueberry -muffins.jpg',
    comments: 75,
    bookmarks: 45,
    time: 10,
    tag: ['#藍莓','#輕食'],
  },
  {
    id: 7,
    title: '經典日式叉燒拉麵',
    image: '/src/assets/image/Recipes/solo-meal/chashu-ramen.jpg',
    comments: 85,
    bookmarks: 30,
    time: 15,
    tag: ['#和風','#麵'],
  },
  {
    id: 8,
    title: '蔥花溫蕎麥麵',
    image: '/src/assets/image/Recipes/solo-meal/soba.jpg',
    comments: 80,
    bookmarks: 20,
    time: 20,
    tag: ['#和風','#麵'],
  },
  {
    id: 9,
    title: '時蔬牛肉炒麵',
    image: '/src/assets/image/Recipes/solo-meal/beef-fried-noodles.jpg',
    comments: 65,
    bookmarks: 25,
    time: 15,
    tag: ['#牛肉', '#麵'],
  },
  {
    id: 10,
    title: '薑絲牛肉湯麵',
    image: '/src/assets/image/Recipes/solo-meal/beef-soup.jpg',
    comments: 85,
    bookmarks: 30,
    time: 25,
    tag: ['#牛肉', '#麵'],
  },
  {
    id: 11,
    title: '越南生牛肉河粉',
    image: '/src/assets/image/Recipes/solo-meal/raw-beef-pho.jpg',
    comments: 80,
    bookmarks: 20,
    time: 20,
    tag: ['#牛肉', '#麵'],
  },
  {
    id: 12,
    title: '香煎雞肉凱薩沙拉',
    image: '/src/assets/image/Recipes/solo-meal/caesar-salad.jpg',
    comments: 65,
    bookmarks: 25,
    time: 15,
    tag: ['#輕食', '#雞肉'],
  },
  {
    id: 13,
    title: '經典魯賓三明治',
    image: '/src/assets/image/Recipes/solo-meal/reuben-sandwich.jpg',
    comments: 85,
    bookmarks: 30,
    time: 25,
    tag: ['#輕食'],
  },
  {
    id: 14,
    title: '爐烤羊排與季節時蔬',
    image: '/src/assets/image/Recipes/solo-meal/oven-baked-pork-chops.jpg',
    comments: 80,
    bookmarks: 20,
    time: 20,
    tag: ['#羊肉'],
  },
  {
    id: 15,
    title: '鮭魚卵蓋飯',
    image: '/src/assets/image/Recipes/solo-meal/salmon-roe-bowl.jpg',
    comments: 65,
    bookmarks: 25,
    time: 15,
    tag: ['#海鮮','#飯'],
  },
  {
    id: 16,
    title: '黃金炸水餃',
    image: '/src/assets/image/Recipes/solo-meal/fried-dumplings.jpg',
    comments: 85,
    bookmarks: 30,
    time: 25,
    tag: ['#豬肉'],
  },
  {
    id: 17,
    title: '台灣蚵仔麵線',
    image: '/src/assets/image/Recipes/solo-meal/oyster-noodles.jpg',
    comments: 80,
    bookmarks: 20,
    time: 20,
    tag: ['#海鮮','#麵'],
  },
  {
    id: 18,
    title: '鮮肉蒸餃',
    image: '/src/assets/image/Recipes/solo-meal/steamed-dumplings.jpg',
    comments: 65,
    bookmarks: 25,
    time: 15,
    tag: ['#豬肉'],
  },
];
